apiVersion: apps/v1
kind: Deployment
metadata:
  name: cofrap-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cofrap-frontend
  template:
    metadata:
      labels:
        app: cofrap-frontend
    spec:
      containers:
        - name: cofrap-frontend
          image: marcopyre/cofrap-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: OPENFAAS_GATEWAY
              value: "http://gateway.openfaas:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cofrap-frontend
spec:
  type: NodePort
  selector:
    app: cofrap-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000 
