# Ce fichier est un exemple de configuration pour un cluster K3S
# Il peut être utilisé avec k3sup pour déployer rapidement un cluster K3S

# Configuration du nœud de contrôle (control-plane)
control_plane:
  hostname: k3s-master
  ip: 192.168.1.10
  user: ubuntu
  ssh_key: ~/.ssh/id_rsa
  k3s_version: v1.26.5+k3s1
  k3s_extra_args:
    - --disable=traefik  # Nous utiliserons nginx-ingress à la place
    - --disable=servicelb  # Nous utiliserons MetalLB à la place

# Configuration des nœuds de travail (workers)
workers:
  - hostname: k3s-worker-1
    ip: 192.168.1.11
    user: ubuntu
    ssh_key: ~/.ssh/id_rsa
    k3s_version: v1.26.5+k3s1
  
  - hostname: k3s-worker-2
    ip: 192.168.1.12
    user: ubuntu
    ssh_key: ~/.ssh/id_rsa
    k3s_version: v1.26.5+k3s1

# Configuration de MetalLB pour le load balancer
metallb:
  namespace: metallb-system
  address_pool:
    name: default
    protocol: layer2
    addresses:
      - 192.168.1.240-192.168.1.250

# Configuration de nginx-ingress pour l'ingress controller
nginx_ingress:
  namespace: ingress-nginx
  version: 1.8.0
